import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IOrders, Orders } from 'app/shared/model/orders.model';
import { OrdersService } from './orders.service';

@Component({
  selector: 'jhi-orders-update',
  templateUrl: './orders-update.component.html'
})
export class OrdersUpdateComponent implements OnInit {
  isSaving = false;
  ordOrderDtDp: any;
  ordRushRequestDueDtDp: any;
  ordOrgDuedateDp: any;
  ordProDuedateDp: any;
  ordUcdpFinalSubmissionDtDp: any;
  ordLoanEstimatedCloseDtDp: any;
  ordLoanBorrowerRequestedCloseDtDp: any;
  ordRequestRrvendorAppraisalDraftRcvdDtDp: any;
  ordValuationDueToClientDtDp: any;
  ordValuationReportRecivedDtDp: any;
  ordValuationCompletionDtDp: any;
  ordReviewDtDp: any;

  editForm = this.fb.group({
    id: [],
    ordNumber: [null, [Validators.required, Validators.maxLength(30)]],
    ordStageCd: [null, [Validators.required, Validators.maxLength(30)]],
    ordOrgOrderStatusCd: [null, [Validators.required, Validators.maxLength(30)]],
    ordCmpOrderStatusCd: [null, [Validators.required, Validators.maxLength(30)]],
    ordProOrderStatusCd: [null, [Validators.required, Validators.maxLength(30)]],
    ordCmpNbr: [null, [Validators.maxLength(30)]],
    ordBrnNbr: [null, [Validators.maxLength(30)]],
    ordProNbr: [null, [Validators.maxLength(30)]],
    ordProductCode: [null, [Validators.maxLength(30)]],
    ordOriginalValueAmt: [null, [Validators.required]],
    ordParentTrackingNbr: [null, [Validators.maxLength(50)]],
    ordUserNbr: [null, [Validators.maxLength(30)]],
    ordOrderDt: [null, [Validators.required]],
    ordRushRequestDueDt: [],
    ordOrgInstructions: [null, [Validators.maxLength(240)]],
    ordOrgOtherInstructions: [null, [Validators.maxLength(240)]],
    ordMultiOrderInd: [null, [Validators.required]],
    ordOrgDuedate: [],
    ordProDuedate: [],
    ordUcdpDataFnmaSubmitToUcdpInd: [null, [Validators.required]],
    ordUcdpDataFnmaServicerNbr: [null, [Validators.maxLength(30)]],
    ordUcdpDataFhlmcSubmitToUcdpInd: [null, [Validators.required]],
    ordUcdpDataFhlmcIdentificationNbr: [null, [Validators.maxLength(30)]],
    ordUcdpDataUcdpBussinessUnitNbr: [null, [Validators.maxLength(30)]],
    ordUcdpSdFnamaDocumentId: [null, [Validators.maxLength(30)]],
    ordUcdpSdFnmaSubmissionStatusId: [null, [Validators.maxLength(80)]],
    ordUcdpSdFhlmcDocumentFileCd: [null, [Validators.maxLength(80)]],
    ordUcdpSdEadSubmissionStatusCd: [null, [Validators.maxLength(80)]],
    ordUcdpFinalSubmissionDt: [],
    ordLoanNbr: [null, [Validators.maxLength(30)]],
    ordloanOldLoanNbr: [null, [Validators.maxLength(30)]],
    ordLoanProgram: [null, [Validators.maxLength(80)]],
    ordLoanPurpose: [null, [Validators.maxLength(80)]],
    ordLoanType: [null, [Validators.maxLength(80)]],
    ordLoanAmt: [null, [Validators.required]],
    ordLoanQualifyingValueAmt: [null, [Validators.required]],
    ordLoanSalesPriceAmt: [null, [Validators.required]],
    ordLoanBorrowerLastName: [null, [Validators.maxLength(30)]],
    ordLoanBorrowerFirstName: [null, [Validators.maxLength(30)]],
    ordLoanBorrowerMiddleName: [null, [Validators.maxLength(30)]],
    ordLoanBorrowerIsCoBorrowerInd: [null, [Validators.required]],
    ordLoanFhaCaseNbr: [null, [Validators.maxLength(30)]],
    ordLoanDeedRestrictionInd: [null, [Validators.required]],
    ordLoanEstimatedCloseDt: [],
    ordLoanHpmlInd: [null, [Validators.required]],
    ordLoanIsNewConstructionInd: [null, [Validators.required]],
    ordLoanCustomerSegmentCode: [null, [Validators.maxLength(30)]],
    ordLoanNonSubjectPropertyInd: [null, [Validators.required]],
    ordLoanBorrowerRequestedCloseDt: [],
    ordPropertyTypeCd: [null, [Validators.maxLength(30)]],
    ordPropertyAddress1: [null, [Validators.maxLength(80)]],
    ordPropertyAddress2: [null, [Validators.maxLength(80)]],
    ordPropertyCity: [null, [Validators.maxLength(80)]],
    ordPropertyStateCd: [null, [Validators.maxLength(30)]],
    ordPropertyZip: [null, [Validators.maxLength(30)]],
    ordPropertyCounty: [null, [Validators.maxLength(80)]],
    ordPropertyLatitue: [null, [Validators.maxLength(80)]],
    ordPropertyLongitude: [null, [Validators.maxLength(80)]],
    ordPropertyProjectName: [null, [Validators.maxLength(80)]],
    ordContact1TypeCd: [],
    ordContact1Name: [null, [Validators.maxLength(120)]],
    ordContact1WorkPhone: [],
    ordContact1HomePhone: [],
    ordContact1CellPhone: [],
    ordContact1OtherCellPhone: [],
    ordContact1Email: [null, [Validators.maxLength(80)]],
    ordContact1OtherEmail: [null, [Validators.maxLength(80)]],
    ordContact2TypeCd: [null, [Validators.maxLength(30)]],
    ordContact2Name: [null, [Validators.maxLength(120)]],
    ordContact2WorkPhone: [],
    ordContact2HomePhone: [],
    ordContact2CellPhone: [],
    ordContact2OtherCellPhone: [],
    ordContact2Email: [null, [Validators.maxLength(80)]],
    ordContact2OtherEmail: [null, [Validators.maxLength(80)]],
    ordContact3TypeCd: [null, [Validators.maxLength(30)]],
    ordContact3Name: [null, [Validators.maxLength(120)]],
    ordContact3WorkPhone: [],
    ordContact3HomePhone: [],
    ordContact3CellPhone: [],
    ordContact3OtherCellPhone: [],
    ordContact3Email: [null, [Validators.maxLength(80)]],
    ordContact3OtherEmail: [null, [Validators.maxLength(80)]],
    ordRequestRrStatusCd: [null, [Validators.maxLength(30)]],
    ordRequestRrVendorAppraisalId: [null, [Validators.maxLength(80)]],
    ordRequestRrvendorAppraisalDraftRcvdDt: [],
    ordRequestRrXmlFormId: [null, [Validators.maxLength(80)]],
    ordRequestRrPdfFormId: [null, [Validators.maxLength(80)]],
    ordRequestRrApprFileDataSourcCd: [null, [Validators.maxLength(30)]],
    ordRequestRrReportValueAmt: [null, [Validators.required]],
    ordRequestRrAppraisalCompanyName: [null, [Validators.maxLength(80)]],
    ordRequestRrvendorName: [null, [Validators.maxLength(80)]],
    ordRequestRrvendorLicenseNbr: [null, [Validators.maxLength(50)]],
    ordRequestRrvendorLicenseStateCd: [null, [Validators.maxLength(30)]],
    ordValuationCompletedProduct: [null, [Validators.maxLength(30)]],
    ordValuationDueToClientDt: [],
    ordValuationReportRecivedDt: [],
    ordValuationCompletionDt: [],
    ordValuationReportStatusCd: [null, [Validators.maxLength(30)]],
    ordValuationAppraisedValueAmt: [null, [Validators.required]],
    ordValuationBpoMarketValueAmt: [null, [Validators.required]],
    ordValuationBpoAsIsAmt: [null, [Validators.required]],
    ordValuationBpoAsRepairedValueAmt: [null, [Validators.required]],
    ordValuationRedFlagCode: [null, [Validators.maxLength(30)]],
    ordValuationRedFlagDesc: [null, [Validators.maxLength(80)]],
    ordValuationAmcAppraisalId: [null, [Validators.maxLength(80)]],
    ordValuationFinalReviewId: [],
    ordReviewRecommendedValueAmt: [null, [Validators.required]],
    ordReviewDt: [],
    ordReviewRecommendedActionCd: [null, [Validators.maxLength(80)]],
    ordReviewReviewerDecisionCd: [null, [Validators.maxLength(80)]],
    ordReviewReviewScore: [null, [Validators.maxLength(80)]],
    ordReviewFormUsed: [null, [Validators.maxLength(80)]],
    ordReviewProviderOnWatchListInd: [null, [Validators.required]],
    ordReviewCuredValueAmt: [null, [Validators.required]],
    ordReviewFinalRecommendedActionCd: [null, [Validators.maxLength(80)]]
  });

  constructor(protected ordersService: OrdersService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ orders }) => {
      this.updateForm(orders);
    });
  }

  updateForm(orders: IOrders): void {
    this.editForm.patchValue({
      id: orders.id,
      ordNumber: orders.ordNumber,
      ordStageCd: orders.ordStageCd,
      ordOrgOrderStatusCd: orders.ordOrgOrderStatusCd,
      ordCmpOrderStatusCd: orders.ordCmpOrderStatusCd,
      ordProOrderStatusCd: orders.ordProOrderStatusCd,
      ordCmpNbr: orders.ordCmpNbr,
      ordBrnNbr: orders.ordBrnNbr,
      ordProNbr: orders.ordProNbr,
      ordProductCode: orders.ordProductCode,
      ordOriginalValueAmt: orders.ordOriginalValueAmt,
      ordParentTrackingNbr: orders.ordParentTrackingNbr,
      ordUserNbr: orders.ordUserNbr,
      ordOrderDt: orders.ordOrderDt,
      ordRushRequestDueDt: orders.ordRushRequestDueDt,
      ordOrgInstructions: orders.ordOrgInstructions,
      ordOrgOtherInstructions: orders.ordOrgOtherInstructions,
      ordMultiOrderInd: orders.ordMultiOrderInd,
      ordOrgDuedate: orders.ordOrgDuedate,
      ordProDuedate: orders.ordProDuedate,
      ordUcdpDataFnmaSubmitToUcdpInd: orders.ordUcdpDataFnmaSubmitToUcdpInd,
      ordUcdpDataFnmaServicerNbr: orders.ordUcdpDataFnmaServicerNbr,
      ordUcdpDataFhlmcSubmitToUcdpInd: orders.ordUcdpDataFhlmcSubmitToUcdpInd,
      ordUcdpDataFhlmcIdentificationNbr: orders.ordUcdpDataFhlmcIdentificationNbr,
      ordUcdpDataUcdpBussinessUnitNbr: orders.ordUcdpDataUcdpBussinessUnitNbr,
      ordUcdpSdFnamaDocumentId: orders.ordUcdpSdFnamaDocumentId,
      ordUcdpSdFnmaSubmissionStatusId: orders.ordUcdpSdFnmaSubmissionStatusId,
      ordUcdpSdFhlmcDocumentFileCd: orders.ordUcdpSdFhlmcDocumentFileCd,
      ordUcdpSdEadSubmissionStatusCd: orders.ordUcdpSdEadSubmissionStatusCd,
      ordUcdpFinalSubmissionDt: orders.ordUcdpFinalSubmissionDt,
      ordLoanNbr: orders.ordLoanNbr,
      ordloanOldLoanNbr: orders.ordloanOldLoanNbr,
      ordLoanProgram: orders.ordLoanProgram,
      ordLoanPurpose: orders.ordLoanPurpose,
      ordLoanType: orders.ordLoanType,
      ordLoanAmt: orders.ordLoanAmt,
      ordLoanQualifyingValueAmt: orders.ordLoanQualifyingValueAmt,
      ordLoanSalesPriceAmt: orders.ordLoanSalesPriceAmt,
      ordLoanBorrowerLastName: orders.ordLoanBorrowerLastName,
      ordLoanBorrowerFirstName: orders.ordLoanBorrowerFirstName,
      ordLoanBorrowerMiddleName: orders.ordLoanBorrowerMiddleName,
      ordLoanBorrowerIsCoBorrowerInd: orders.ordLoanBorrowerIsCoBorrowerInd,
      ordLoanFhaCaseNbr: orders.ordLoanFhaCaseNbr,
      ordLoanDeedRestrictionInd: orders.ordLoanDeedRestrictionInd,
      ordLoanEstimatedCloseDt: orders.ordLoanEstimatedCloseDt,
      ordLoanHpmlInd: orders.ordLoanHpmlInd,
      ordLoanIsNewConstructionInd: orders.ordLoanIsNewConstructionInd,
      ordLoanCustomerSegmentCode: orders.ordLoanCustomerSegmentCode,
      ordLoanNonSubjectPropertyInd: orders.ordLoanNonSubjectPropertyInd,
      ordLoanBorrowerRequestedCloseDt: orders.ordLoanBorrowerRequestedCloseDt,
      ordPropertyTypeCd: orders.ordPropertyTypeCd,
      ordPropertyAddress1: orders.ordPropertyAddress1,
      ordPropertyAddress2: orders.ordPropertyAddress2,
      ordPropertyCity: orders.ordPropertyCity,
      ordPropertyStateCd: orders.ordPropertyStateCd,
      ordPropertyZip: orders.ordPropertyZip,
      ordPropertyCounty: orders.ordPropertyCounty,
      ordPropertyLatitue: orders.ordPropertyLatitue,
      ordPropertyLongitude: orders.ordPropertyLongitude,
      ordPropertyProjectName: orders.ordPropertyProjectName,
      ordContact1TypeCd: orders.ordContact1TypeCd,
      ordContact1Name: orders.ordContact1Name,
      ordContact1WorkPhone: orders.ordContact1WorkPhone,
      ordContact1HomePhone: orders.ordContact1HomePhone,
      ordContact1CellPhone: orders.ordContact1CellPhone,
      ordContact1OtherCellPhone: orders.ordContact1OtherCellPhone,
      ordContact1Email: orders.ordContact1Email,
      ordContact1OtherEmail: orders.ordContact1OtherEmail,
      ordContact2TypeCd: orders.ordContact2TypeCd,
      ordContact2Name: orders.ordContact2Name,
      ordContact2WorkPhone: orders.ordContact2WorkPhone,
      ordContact2HomePhone: orders.ordContact2HomePhone,
      ordContact2CellPhone: orders.ordContact2CellPhone,
      ordContact2OtherCellPhone: orders.ordContact2OtherCellPhone,
      ordContact2Email: orders.ordContact2Email,
      ordContact2OtherEmail: orders.ordContact2OtherEmail,
      ordContact3TypeCd: orders.ordContact3TypeCd,
      ordContact3Name: orders.ordContact3Name,
      ordContact3WorkPhone: orders.ordContact3WorkPhone,
      ordContact3HomePhone: orders.ordContact3HomePhone,
      ordContact3CellPhone: orders.ordContact3CellPhone,
      ordContact3OtherCellPhone: orders.ordContact3OtherCellPhone,
      ordContact3Email: orders.ordContact3Email,
      ordContact3OtherEmail: orders.ordContact3OtherEmail,
      ordRequestRrStatusCd: orders.ordRequestRrStatusCd,
      ordRequestRrVendorAppraisalId: orders.ordRequestRrVendorAppraisalId,
      ordRequestRrvendorAppraisalDraftRcvdDt: orders.ordRequestRrvendorAppraisalDraftRcvdDt,
      ordRequestRrXmlFormId: orders.ordRequestRrXmlFormId,
      ordRequestRrPdfFormId: orders.ordRequestRrPdfFormId,
      ordRequestRrApprFileDataSourcCd: orders.ordRequestRrApprFileDataSourcCd,
      ordRequestRrReportValueAmt: orders.ordRequestRrReportValueAmt,
      ordRequestRrAppraisalCompanyName: orders.ordRequestRrAppraisalCompanyName,
      ordRequestRrvendorName: orders.ordRequestRrvendorName,
      ordRequestRrvendorLicenseNbr: orders.ordRequestRrvendorLicenseNbr,
      ordRequestRrvendorLicenseStateCd: orders.ordRequestRrvendorLicenseStateCd,
      ordValuationCompletedProduct: orders.ordValuationCompletedProduct,
      ordValuationDueToClientDt: orders.ordValuationDueToClientDt,
      ordValuationReportRecivedDt: orders.ordValuationReportRecivedDt,
      ordValuationCompletionDt: orders.ordValuationCompletionDt,
      ordValuationReportStatusCd: orders.ordValuationReportStatusCd,
      ordValuationAppraisedValueAmt: orders.ordValuationAppraisedValueAmt,
      ordValuationBpoMarketValueAmt: orders.ordValuationBpoMarketValueAmt,
      ordValuationBpoAsIsAmt: orders.ordValuationBpoAsIsAmt,
      ordValuationBpoAsRepairedValueAmt: orders.ordValuationBpoAsRepairedValueAmt,
      ordValuationRedFlagCode: orders.ordValuationRedFlagCode,
      ordValuationRedFlagDesc: orders.ordValuationRedFlagDesc,
      ordValuationAmcAppraisalId: orders.ordValuationAmcAppraisalId,
      ordValuationFinalReviewId: orders.ordValuationFinalReviewId,
      ordReviewRecommendedValueAmt: orders.ordReviewRecommendedValueAmt,
      ordReviewDt: orders.ordReviewDt,
      ordReviewRecommendedActionCd: orders.ordReviewRecommendedActionCd,
      ordReviewReviewerDecisionCd: orders.ordReviewReviewerDecisionCd,
      ordReviewReviewScore: orders.ordReviewReviewScore,
      ordReviewFormUsed: orders.ordReviewFormUsed,
      ordReviewProviderOnWatchListInd: orders.ordReviewProviderOnWatchListInd,
      ordReviewCuredValueAmt: orders.ordReviewCuredValueAmt,
      ordReviewFinalRecommendedActionCd: orders.ordReviewFinalRecommendedActionCd
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const orders = this.createFromForm();
    if (orders.id !== undefined) {
      this.subscribeToSaveResponse(this.ordersService.update(orders));
    } else {
      this.subscribeToSaveResponse(this.ordersService.create(orders));
    }
  }

  private createFromForm(): IOrders {
    return {
      ...new Orders(),
      id: this.editForm.get(['id'])!.value,
      ordNumber: this.editForm.get(['ordNumber'])!.value,
      ordStageCd: this.editForm.get(['ordStageCd'])!.value,
      ordOrgOrderStatusCd: this.editForm.get(['ordOrgOrderStatusCd'])!.value,
      ordCmpOrderStatusCd: this.editForm.get(['ordCmpOrderStatusCd'])!.value,
      ordProOrderStatusCd: this.editForm.get(['ordProOrderStatusCd'])!.value,
      ordCmpNbr: this.editForm.get(['ordCmpNbr'])!.value,
      ordBrnNbr: this.editForm.get(['ordBrnNbr'])!.value,
      ordProNbr: this.editForm.get(['ordProNbr'])!.value,
      ordProductCode: this.editForm.get(['ordProductCode'])!.value,
      ordOriginalValueAmt: this.editForm.get(['ordOriginalValueAmt'])!.value,
      ordParentTrackingNbr: this.editForm.get(['ordParentTrackingNbr'])!.value,
      ordUserNbr: this.editForm.get(['ordUserNbr'])!.value,
      ordOrderDt: this.editForm.get(['ordOrderDt'])!.value,
      ordRushRequestDueDt: this.editForm.get(['ordRushRequestDueDt'])!.value,
      ordOrgInstructions: this.editForm.get(['ordOrgInstructions'])!.value,
      ordOrgOtherInstructions: this.editForm.get(['ordOrgOtherInstructions'])!.value,
      ordMultiOrderInd: this.editForm.get(['ordMultiOrderInd'])!.value,
      ordOrgDuedate: this.editForm.get(['ordOrgDuedate'])!.value,
      ordProDuedate: this.editForm.get(['ordProDuedate'])!.value,
      ordUcdpDataFnmaSubmitToUcdpInd: this.editForm.get(['ordUcdpDataFnmaSubmitToUcdpInd'])!.value,
      ordUcdpDataFnmaServicerNbr: this.editForm.get(['ordUcdpDataFnmaServicerNbr'])!.value,
      ordUcdpDataFhlmcSubmitToUcdpInd: this.editForm.get(['ordUcdpDataFhlmcSubmitToUcdpInd'])!.value,
      ordUcdpDataFhlmcIdentificationNbr: this.editForm.get(['ordUcdpDataFhlmcIdentificationNbr'])!.value,
      ordUcdpDataUcdpBussinessUnitNbr: this.editForm.get(['ordUcdpDataUcdpBussinessUnitNbr'])!.value,
      ordUcdpSdFnamaDocumentId: this.editForm.get(['ordUcdpSdFnamaDocumentId'])!.value,
      ordUcdpSdFnmaSubmissionStatusId: this.editForm.get(['ordUcdpSdFnmaSubmissionStatusId'])!.value,
      ordUcdpSdFhlmcDocumentFileCd: this.editForm.get(['ordUcdpSdFhlmcDocumentFileCd'])!.value,
      ordUcdpSdEadSubmissionStatusCd: this.editForm.get(['ordUcdpSdEadSubmissionStatusCd'])!.value,
      ordUcdpFinalSubmissionDt: this.editForm.get(['ordUcdpFinalSubmissionDt'])!.value,
      ordLoanNbr: this.editForm.get(['ordLoanNbr'])!.value,
      ordloanOldLoanNbr: this.editForm.get(['ordloanOldLoanNbr'])!.value,
      ordLoanProgram: this.editForm.get(['ordLoanProgram'])!.value,
      ordLoanPurpose: this.editForm.get(['ordLoanPurpose'])!.value,
      ordLoanType: this.editForm.get(['ordLoanType'])!.value,
      ordLoanAmt: this.editForm.get(['ordLoanAmt'])!.value,
      ordLoanQualifyingValueAmt: this.editForm.get(['ordLoanQualifyingValueAmt'])!.value,
      ordLoanSalesPriceAmt: this.editForm.get(['ordLoanSalesPriceAmt'])!.value,
      ordLoanBorrowerLastName: this.editForm.get(['ordLoanBorrowerLastName'])!.value,
      ordLoanBorrowerFirstName: this.editForm.get(['ordLoanBorrowerFirstName'])!.value,
      ordLoanBorrowerMiddleName: this.editForm.get(['ordLoanBorrowerMiddleName'])!.value,
      ordLoanBorrowerIsCoBorrowerInd: this.editForm.get(['ordLoanBorrowerIsCoBorrowerInd'])!.value,
      ordLoanFhaCaseNbr: this.editForm.get(['ordLoanFhaCaseNbr'])!.value,
      ordLoanDeedRestrictionInd: this.editForm.get(['ordLoanDeedRestrictionInd'])!.value,
      ordLoanEstimatedCloseDt: this.editForm.get(['ordLoanEstimatedCloseDt'])!.value,
      ordLoanHpmlInd: this.editForm.get(['ordLoanHpmlInd'])!.value,
      ordLoanIsNewConstructionInd: this.editForm.get(['ordLoanIsNewConstructionInd'])!.value,
      ordLoanCustomerSegmentCode: this.editForm.get(['ordLoanCustomerSegmentCode'])!.value,
      ordLoanNonSubjectPropertyInd: this.editForm.get(['ordLoanNonSubjectPropertyInd'])!.value,
      ordLoanBorrowerRequestedCloseDt: this.editForm.get(['ordLoanBorrowerRequestedCloseDt'])!.value,
      ordPropertyTypeCd: this.editForm.get(['ordPropertyTypeCd'])!.value,
      ordPropertyAddress1: this.editForm.get(['ordPropertyAddress1'])!.value,
      ordPropertyAddress2: this.editForm.get(['ordPropertyAddress2'])!.value,
      ordPropertyCity: this.editForm.get(['ordPropertyCity'])!.value,
      ordPropertyStateCd: this.editForm.get(['ordPropertyStateCd'])!.value,
      ordPropertyZip: this.editForm.get(['ordPropertyZip'])!.value,
      ordPropertyCounty: this.editForm.get(['ordPropertyCounty'])!.value,
      ordPropertyLatitue: this.editForm.get(['ordPropertyLatitue'])!.value,
      ordPropertyLongitude: this.editForm.get(['ordPropertyLongitude'])!.value,
      ordPropertyProjectName: this.editForm.get(['ordPropertyProjectName'])!.value,
      ordContact1TypeCd: this.editForm.get(['ordContact1TypeCd'])!.value,
      ordContact1Name: this.editForm.get(['ordContact1Name'])!.value,
      ordContact1WorkPhone: this.editForm.get(['ordContact1WorkPhone'])!.value,
      ordContact1HomePhone: this.editForm.get(['ordContact1HomePhone'])!.value,
      ordContact1CellPhone: this.editForm.get(['ordContact1CellPhone'])!.value,
      ordContact1OtherCellPhone: this.editForm.get(['ordContact1OtherCellPhone'])!.value,
      ordContact1Email: this.editForm.get(['ordContact1Email'])!.value,
      ordContact1OtherEmail: this.editForm.get(['ordContact1OtherEmail'])!.value,
      ordContact2TypeCd: this.editForm.get(['ordContact2TypeCd'])!.value,
      ordContact2Name: this.editForm.get(['ordContact2Name'])!.value,
      ordContact2WorkPhone: this.editForm.get(['ordContact2WorkPhone'])!.value,
      ordContact2HomePhone: this.editForm.get(['ordContact2HomePhone'])!.value,
      ordContact2CellPhone: this.editForm.get(['ordContact2CellPhone'])!.value,
      ordContact2OtherCellPhone: this.editForm.get(['ordContact2OtherCellPhone'])!.value,
      ordContact2Email: this.editForm.get(['ordContact2Email'])!.value,
      ordContact2OtherEmail: this.editForm.get(['ordContact2OtherEmail'])!.value,
      ordContact3TypeCd: this.editForm.get(['ordContact3TypeCd'])!.value,
      ordContact3Name: this.editForm.get(['ordContact3Name'])!.value,
      ordContact3WorkPhone: this.editForm.get(['ordContact3WorkPhone'])!.value,
      ordContact3HomePhone: this.editForm.get(['ordContact3HomePhone'])!.value,
      ordContact3CellPhone: this.editForm.get(['ordContact3CellPhone'])!.value,
      ordContact3OtherCellPhone: this.editForm.get(['ordContact3OtherCellPhone'])!.value,
      ordContact3Email: this.editForm.get(['ordContact3Email'])!.value,
      ordContact3OtherEmail: this.editForm.get(['ordContact3OtherEmail'])!.value,
      ordRequestRrStatusCd: this.editForm.get(['ordRequestRrStatusCd'])!.value,
      ordRequestRrVendorAppraisalId: this.editForm.get(['ordRequestRrVendorAppraisalId'])!.value,
      ordRequestRrvendorAppraisalDraftRcvdDt: this.editForm.get(['ordRequestRrvendorAppraisalDraftRcvdDt'])!.value,
      ordRequestRrXmlFormId: this.editForm.get(['ordRequestRrXmlFormId'])!.value,
      ordRequestRrPdfFormId: this.editForm.get(['ordRequestRrPdfFormId'])!.value,
      ordRequestRrApprFileDataSourcCd: this.editForm.get(['ordRequestRrApprFileDataSourcCd'])!.value,
      ordRequestRrReportValueAmt: this.editForm.get(['ordRequestRrReportValueAmt'])!.value,
      ordRequestRrAppraisalCompanyName: this.editForm.get(['ordRequestRrAppraisalCompanyName'])!.value,
      ordRequestRrvendorName: this.editForm.get(['ordRequestRrvendorName'])!.value,
      ordRequestRrvendorLicenseNbr: this.editForm.get(['ordRequestRrvendorLicenseNbr'])!.value,
      ordRequestRrvendorLicenseStateCd: this.editForm.get(['ordRequestRrvendorLicenseStateCd'])!.value,
      ordValuationCompletedProduct: this.editForm.get(['ordValuationCompletedProduct'])!.value,
      ordValuationDueToClientDt: this.editForm.get(['ordValuationDueToClientDt'])!.value,
      ordValuationReportRecivedDt: this.editForm.get(['ordValuationReportRecivedDt'])!.value,
      ordValuationCompletionDt: this.editForm.get(['ordValuationCompletionDt'])!.value,
      ordValuationReportStatusCd: this.editForm.get(['ordValuationReportStatusCd'])!.value,
      ordValuationAppraisedValueAmt: this.editForm.get(['ordValuationAppraisedValueAmt'])!.value,
      ordValuationBpoMarketValueAmt: this.editForm.get(['ordValuationBpoMarketValueAmt'])!.value,
      ordValuationBpoAsIsAmt: this.editForm.get(['ordValuationBpoAsIsAmt'])!.value,
      ordValuationBpoAsRepairedValueAmt: this.editForm.get(['ordValuationBpoAsRepairedValueAmt'])!.value,
      ordValuationRedFlagCode: this.editForm.get(['ordValuationRedFlagCode'])!.value,
      ordValuationRedFlagDesc: this.editForm.get(['ordValuationRedFlagDesc'])!.value,
      ordValuationAmcAppraisalId: this.editForm.get(['ordValuationAmcAppraisalId'])!.value,
      ordValuationFinalReviewId: this.editForm.get(['ordValuationFinalReviewId'])!.value,
      ordReviewRecommendedValueAmt: this.editForm.get(['ordReviewRecommendedValueAmt'])!.value,
      ordReviewDt: this.editForm.get(['ordReviewDt'])!.value,
      ordReviewRecommendedActionCd: this.editForm.get(['ordReviewRecommendedActionCd'])!.value,
      ordReviewReviewerDecisionCd: this.editForm.get(['ordReviewReviewerDecisionCd'])!.value,
      ordReviewReviewScore: this.editForm.get(['ordReviewReviewScore'])!.value,
      ordReviewFormUsed: this.editForm.get(['ordReviewFormUsed'])!.value,
      ordReviewProviderOnWatchListInd: this.editForm.get(['ordReviewProviderOnWatchListInd'])!.value,
      ordReviewCuredValueAmt: this.editForm.get(['ordReviewCuredValueAmt'])!.value,
      ordReviewFinalRecommendedActionCd: this.editForm.get(['ordReviewFinalRecommendedActionCd'])!.value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IOrders>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }
}
